version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.5.3-node
      environment:
        RAILS_ENV: test
        MYSQL_HOST: 127.0.0.1
        MYSQL_USERNAME: 'root'
        MYSQL_PASSWORD: ''
        MYSQL_PORT: 3306

    - image: circleci/mysql:5.7
      environment:
        MYSQL_DATABASE: chat_space_test
        MYSQL_ALLOW_EMPTY_PASSWORD: true
        MYSQL_ROOT_HOST: '%'

    working_directory: ~/chat_space

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command:
          bundle install --jobs=4 --retry=3 --path vendor/bundle
  
    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    # Database setup
    - run: rm ./config/database.yml
    - run: mv ./config/database.yml.ci ./config/database.yml

    - run:
        name: Prepare db
        command:
          bundle exec rake db:create db:schema:load --trace

    # run tests!
    - run:
        name: Rubocop
        command: bundle exec rubocop -c .rubocop_todo.yml

    # collect reports
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results